INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (1, N'Rajiv Patil', N'M', N'Pune', N'rajiv.patil@transflower.in', 26)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (2, N'Komal Varma', N'F', N'Mumbai', N'komal.varma@transflower.in', 24)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (3, N'Ganesh More', N'M', N'Pune', N'ganesh.more@transflower.in', 28)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (4, N'Raghu Pande', N'M', N'Delhi', N'raghu.pande@transflower.in', 25)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (6, N'Manisha Athwale', N'F', N'Mumbai', N'manisha.athwale', 26)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (7, N'Rahul Navale', N'M', N'Pune', N'rahul.navale@transflower.in', 29)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (8, N'Shubhankar Tambade', N'M', N'Pune', N'shubhankar.tambade@transflower.in', 24)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (9, N'Omkar Hinge', N'M', N'Pune', N'omkar.hinge@transflower.in', 24)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (10, N'Shrikant Patil', N'M', N'Kolhapur', N'shrikant.patil@transflower.in', 29)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (11, N'Reetu Sharma', N'F', N'Delhi', N'reetu.sharma@transflower.in', 30)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (12, N'Kanchan Nene', N'F', N'Mumbai', N'kanchan.nene@transflower.in', 28)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (13, N'Shubhangi Tambade', N'F', N'Pune', N'shubhangi.tambade@transflower.in', 39)
INSERT INTO [dbo].[employees] ([Id], [Name], [Gender], [City], [Email], [Age]) VALUES (14, N'Ravi Tambade', N'M', N'Pune', N'ravi.tamabde@transflower.in', 42)

